### ISSUE TITLE
iPhone tests unable to run on saucelabs

### ISSUE THREAD

**Issue by vvo** [defunctzombie/zuul#162] opened 2015-03-02 09:50 UTC
Following #129 and iphone errors like https://gist.github.com/parshap/f2c0d514de244340ff38:

```txt
- starting: <safari 8 on Mac 10.10>
- starting: <safari 8 on Mac 10.10>
- waiting: <safari 8 on Mac 10.10>
- restarting: <safari 8 on Mac 10.10>
- waiting: <safari 8 on Mac 10.10>
 
Error: Timeout opening url
    at null.<anonymous> (/Users/parshap/projects/js-is-integer/node_modules/zuul/lib/SauceBrowser.js:144:35)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
./node_modules/.bin/zuul --sauce-connect -- test.js  71.73s user 4.29s system 14% cpu 8:46.31 total
```

A saucelabs engineer @sebv told me specify the [appium](http://appium.io/) version in the capabilities (`appium-version`). Tried it with my zuul.yml and it worked perfectly.

I propose to put this directly in the defaults so that we do not get any more iPhone errors.

When saucelabs fixes this then we can revert this fix so that saucelabs will always select latest version.

Incoming PR to solve this.

@parshap here's your issue.

**Comment by rase-** [comment] 2015-03-02 13:30
So the issue is that sometimes they don't pick the latest version automatically or something?

**Comment by vvo** [comment] 2015-03-02 13:32
Yes, going to update this PR to solve mobile issues

**Comment by rase-** [comment] 2015-03-03 23:37
I think we can close this now with the locked appium version in master.

**Closed by rase-** 2015-03-03 23:37 UTC
